# Generated by Django 4.2 on 2023-04-09 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/usuario_defecto.jpg', upload_to='users/', verbose_name='imagen')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre')),
                ('lastName', models.CharField(blank=True, max_length=255, null=True, verbose_name='apellido')),
                ('idU', models.CharField(max_length=6, verbose_name='id_Universidad')),
                ('faculty', models.CharField(choices=[('Ingenieria sistemas', 'Ingenieria sistemas'), ('Ingenieria civil', 'Ingenieria civil'), ('Derecho', 'Derecho'), ('Psicologia', 'Psicologia')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
