# Generated by Django 4.2 on 2023-04-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(choices=[('Ingenieria sistemas', 'Ingenieria sistemas'), ('Ingenieria civil', 'Ingenieria civil'), ('Derecho', 'Derecho'), ('Psicologia', 'Psicologia')], max_length=50, verbose_name='Facultad'),
        ),
    ]
